/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALCULATOR_H_RPCGEN
#define _CALCULATOR_H_RPCGEN

#include <rpc/rpc.h>

#ifdef __cplusplus
extern "C" {
#endif

#define ADD 0
#define SUB 1
#define MUL 2
#define DIV 3

struct CALCULATOR_ARGS {
  int op;
  float arg1;
  float arg2;
};
typedef struct CALCULATOR_ARGS CALCULATOR_ARGS;

#define CALCULATOR_PROG 0x20000001
#define CALCULATOR_VER 1

#if defined(__STDC__) || defined(__cplusplus)
#define CALCULATE 1
extern float *calculate_1(CALCULATOR_ARGS *, CLIENT *);
extern float *calculate_1_svc(CALCULATOR_ARGS *, struct svc_req *);
extern int calculator_prog_1_freeresult(SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define CALCULATE 1
extern float *calculate_1();
extern float *calculate_1_svc();
extern int calculator_prog_1_freeresult();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern bool_t xdr_CALCULATOR_ARGS(XDR *, CALCULATOR_ARGS *);

#else /* K&R C */
extern bool_t xdr_CALCULATOR_ARGS();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALCULATOR_H_RPCGEN */