/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _PC_H_RPCGEN
#define _PC_H_RPCGEN

#define RPCGEN_VERSION	199506

#include <rpc/rpc.h>


#define PC_PROG ((rpc_uint)0x20000001)
#define PC_VERSION ((rpc_uint)1)

#ifdef __cplusplus
#define consume ((rpc_uint)1)
extern "C" char * consume_1(void *, CLIENT *);
extern "C" char * consume_1_svc(void *, struct svc_req *);
#define produce ((rpc_uint)2)
extern "C" char * produce_1(void *, CLIENT *);
extern "C" char * produce_1_svc(void *, struct svc_req *);

#elif __STDC__
#define consume ((rpc_uint)1)
extern  char * consume_1(void *, CLIENT *);
extern  char * consume_1_svc(void *, struct svc_req *);
#define produce ((rpc_uint)2)
extern  char * produce_1(void *, CLIENT *);
extern  char * produce_1_svc(void *, struct svc_req *);

#else /* Old Style C */
#define consume ((rpc_uint)1)
extern  char * consume_1();
extern  char * consume_1_svc();
#define produce ((rpc_uint)2)
extern  char * produce_1();
extern  char * produce_1_svc();
#endif /* Old Style C */

#endif /* !_PC_H_RPCGEN */
