/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "pc.h"

char *
consume_1(argp, rqstp)
	void *argp;
	struct svc_req *rqstp;
{

	static char  result;

	/*
	 * insert server code here
	 */

	return(&result);
}

char *
produce_1(argp, rqstp)
	void *argp;
	struct svc_req *rqstp;
{

	static char  result;

	/*
	 * insert server code here
	 */

	return(&result);
}
