/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _BAKERY_H_RPCGEN
#define _BAKERY_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct BAKERY_REQUEST {
	int client_id;
	char request_type[50];
	char details[100];
};
typedef struct BAKERY_REQUEST BAKERY_REQUEST;

struct BAKERY_RESPONSE {
	int client_id;
	int ticket_number;
	int queue_position;
	char status[100];
};
typedef struct BAKERY_RESPONSE BAKERY_RESPONSE;

#define BAKERY_PROG 0x30000001
#define BAKERY_VER 1

#if defined(__STDC__) || defined(__cplusplus)
#define SUBMIT_REQUEST 1
extern  BAKERY_RESPONSE * submit_request_1(BAKERY_REQUEST *, CLIENT *);
extern  BAKERY_RESPONSE * submit_request_1_svc(BAKERY_REQUEST *, struct svc_req *);
#define GET_TICKET_NUMBER 2
extern  int * get_ticket_number_1(int *, CLIENT *);
extern  int * get_ticket_number_1_svc(int *, struct svc_req *);
#define GET_QUEUE_POSITION 3
extern  int * get_queue_position_1(int *, CLIENT *);
extern  int * get_queue_position_1_svc(int *, struct svc_req *);
extern int bakery_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define SUBMIT_REQUEST 1
extern  BAKERY_RESPONSE * submit_request_1();
extern  BAKERY_RESPONSE * submit_request_1_svc();
#define GET_TICKET_NUMBER 2
extern  int * get_ticket_number_1();
extern  int * get_ticket_number_1_svc();
#define GET_QUEUE_POSITION 3
extern  int * get_queue_position_1();
extern  int * get_queue_position_1_svc();
extern int bakery_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_BAKERY_REQUEST (XDR *, BAKERY_REQUEST*);
extern  bool_t xdr_BAKERY_RESPONSE (XDR *, BAKERY_RESPONSE*);

#else /* K&R C */
extern bool_t xdr_BAKERY_REQUEST ();
extern bool_t xdr_BAKERY_RESPONSE ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_BAKERY_H_RPCGEN */
