/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "bakery.h"

bool_t
xdr_BAKERY_REQUEST (XDR *xdrs, BAKERY_REQUEST *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_int (xdrs, &objp->client_id))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->request_type, 50,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->details, 100,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_BAKERY_RESPONSE (XDR *xdrs, BAKERY_RESPONSE *objp)
{
	register int32_t *buf;

	int i;

	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE (xdrs, 3 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->client_id))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->ticket_number))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->queue_position))
				 return FALSE;

		} else {
		IXDR_PUT_LONG(buf, objp->client_id);
		IXDR_PUT_LONG(buf, objp->ticket_number);
		IXDR_PUT_LONG(buf, objp->queue_position);
		}
		 if (!xdr_vector (xdrs, (char *)objp->status, 100,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE (xdrs, 3 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->client_id))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->ticket_number))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->queue_position))
				 return FALSE;

		} else {
		objp->client_id = IXDR_GET_LONG(buf);
		objp->ticket_number = IXDR_GET_LONG(buf);
		objp->queue_position = IXDR_GET_LONG(buf);
		}
		 if (!xdr_vector (xdrs, (char *)objp->status, 100,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
	 return TRUE;
	}

	 if (!xdr_int (xdrs, &objp->client_id))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->ticket_number))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->queue_position))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->status, 100,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}
